dat <- read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F, sep=';')
colnames(dat) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
datetime <- paste(dat$Date,dat$Time)
dat$DateTimefixed <- strptime(x=datetime,format="%d/%m/%Y %H:%M:%S")
plot(dat$DateTimefixed,dat$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.copy(png,width=480,height=480,file="plot2.png")
dev.off()