dat <- read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F, sep=';')
colnames(dat) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
hist(dat$Global_active_power,xlim=c(0,6),col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.copy(png,width=480,height=480,file="plot1.png")
dev.off()
