dat <- read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F, sep=';')
colnames(dat) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
datetime <- paste(dat$Date,dat$Time)
dat$DateTimefixed <- strptime(x=datetime,format="%d/%m/%Y %H:%M:%S")
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(dat$DateTimefixed,dat$Global_active_power,ylab="GLobal Active Power",xlab="",type="l")
plot(dat$DateTimefixed,dat$Voltage,ylab="Voltage",xlab="datetime",type="l")
plot(dat$DateTimefixed,dat$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
lines(x=dat$DateTimefixed,y=dat$Sub_metering_1,col="black")
lines(x=dat$DateTimefixed,y=dat$Sub_metering_2,col="red")
lines(x=dat$DateTimefixed,y=dat$Sub_metering_3,col="blue")
legend("topright",lty="solid",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n")
plot(dat$DateTimefixed,dat$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type='l"')
dev.off()